services:
    db:
        image: postgres
        volumes:
            - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: "${PASSWORD}"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 1s
            timeout: 5s
            retries: 10
    web:
        build: '.'
        ports:
            - 2017:2017
        links:
            - "db:database"